server:
  port: 9000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caijinkun/cloud-config
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/